### ISSUE TITLE
Where is Zotero/storage?

### ISSUE THREAD

**Issue by madsamjp** [zotero/zotero-android#112]
I'm trying to sync my pdfs using syncthing on android and I cant find the zotero storage directory on my android device to do this. Could you tell me where the storage directory is?

**Comment by dstillman** [comment]
'storage' is an implementation detail of the desktop app. Nothing to do with the Android app.

Files in the Android app can be synced in-app via Zotero Storage or WebDAV.

Please post all questions to the forums.

**Comment by much-doge** [comment]
@dstillman Forgive me for asking, but, has the WebDAV function implemented yet? I haven't seen the option to set up the webdav on my app. there is only account setting. 

Having an official app for the android is a great news by the way

**Comment by dstillman** [comment]
> has the WebDAV function implemented yet?

No. https://forums.zotero.org/discussion/comment/454084/#Comment_454084

**Comment by yuchen-lea** [comment]
When there is no WebDAV function, can we use other software to synchronize storage to a folder on Android and then let zotero read it?

**Comment by artkpv** [comment]
@dstillman  Sorry if it is offtopic. But I'd really love to see external storage as a local folder as it is done on Zoo for Zotero. I wrote at the forum about that: https://forums.zotero.org/discussion/110870/android-possibility-of-external-storage .  I currently have both installed: Zoo for Zotero and Zotero on Android, because I can't open my attachments from my local folder that I sync using Syncthing (manual sync). I'd really love to see the same feature in Zotero on Android as Zoo fro Zotero has: the ability to point at a local directory to get the attachments (pdfs, epubs, etc.). Thanks
