### ISSUE TITLE
Don't use rectangular selection for highlighting

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-android#130]
https://forums.zotero.org/discussion/112908/android-feature-request-annotation-line-and-highlight-tools-issues

I can reproduce this. It shows a rectangular selection area instead of just highlighting text, and it's not possible to end the selection on a new line to the left of the start position.

**Comment by Dima-Android** [comment]
I've looked into it and couldn't find a way how to make rectangle disappear during highlighting and most importantly how to make it allow to select the text to the left of the start of selection on the new line. I've asked PSPDFKIT team for suggestions.

**Comment by kareliot** [comment]
The selection of texts works great without rectangle when no tool is selected. It is then also possible to end the selection on a new line to the left of the start position. But I cannot do anything with the selection. Maybe this could be combined, so that the highlighting selection makes use of the same approach as the selection without tool. In turn, it would be great if I could do something with already selected texts, such as add a highlight or a note.
