### ISSUE TITLE
Zoom level is reset after editing annotation

### ISSUE THREAD

**Issue by dstillman** [zotero/zotero-android#199]
1. Zoom in on an annotation
2. Tap it
3. Tap Done (without making any changes)

The zoom level resets to show the full page instead of staying where it was.

**Comment by atnoir** [comment]
It's also reset after horizontal flipping at double-page view. @dstillman

**Comment by Dima-Android** [comment]
I've looked into what API is available in PSPDFKIT to achieve this and made a bunch of trials and I can't seem to get the desired result out of it.
To explain why I will first describe the current setup in Zotero app:
When you go from PdfScreen to the Annotation editing screen (the one you see when you tap on the annotation) what basically happens is we go from one Activity(Android's terminology) to another Activity. (Well they are technically not activities since we are now using Compose, but side effects are all the same).
When we go to a second activity we have to deinitialize PSPDFKIT's Pdf View that lives inside of the first activity. And when the user goes back from Annotation Screen to Pdf Screen we have to reinitialize PSPDFKIT's Pdf View. This reinitialization cannot be avoided and even if we tried, since the PdfView is a very heavy object it will highly likely get deinitialized by the Android OS for conservation of resources the moment we navigate away to another Activity.

Now you would think that if we were to just save the Pdf View's ViewPort parameters before navigating to Annotation Editing Screen and then would just reinitialize the Pdf View with those parameters on user's return to Pdf Screen that would be it, but unfortunately no.

There are several API's regarding getting currents ViewPort params like: current zoom level, and info on by how much user scrolled document in x or y axises.
But the only API we could use to ask PdfView to scroll document to a desired position is 
scrollTo(@NonNull RectF pdfRect, @IntRange(from = 0L) int pageIndex, long duration, boolean scrollWhenVisible)
The problem is that this API works by asking us to provide the pdfRect of an area in the document which must become visible. 
This API does not take into account zoom levels. So theoretically the way we would use it is that we would save the user's last zoom level, ask PdfView to first zoom the document, and then make a rectangle where the taget annotation is located to become visible by having this API to scrolling there.
What experiments show is that the way it ends up looking after zooming/scrolling by this API is very frequently different from the way user left the ViewPort when user went to AnnotationEditing Screen.
And that's understandable - we cannot pass to PdfView the precise positions of horizontal and vertical scrollbars taking into the account zoom level. Instead we just ask PdfView to make something visible by scrolling to it and living it up to PdfView to actually do it.
It's especially bad in 'Page "Continuous"' setting which allows you to scroll between pages without jumps and lets say you scrolled in such way that you see two pages - bottom half of first page and upper half of second and you tap on annotation located in the bottom part of first page. When you come back from annotation screen you expect it to see it exactly as it were - in the upper portion of your screen, but because of this API you will see it at the bottom of your screen, since API will scroll document just enough to make the annotation visible.
You might say - hey let's just pass to the scrollTo function the pdfRect of the entire visible portion of the document. This might make scrolling to such rect to restore the desired viewPort right? Well no, the pdfRect can only be used to carve a portion of a single page, hence the scrollTo API also demands the pageIndex.

I now think we can solve this in a different way. What if we make the AnnotationEditing screen to not be a separate activity, but just a regular View that would on Phones slide across the screen taking all of its height and width, just like the Sidebar currently does. This will prevent PdfView from being unloaded and we won't have to reinitialize it. Hence it will leave ViewPort in it's exact state after the user is done editing the annotation.
Will take a bit of time to rewire things, but in the end I think it will not only solve this problem, but will actually make some other older fixes that we did in the past regarding annotation editing and Pdf View config editing to become redundant and have them removed from codebase. It will also make the transition between these two screens faster and with no stutter.
